# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
#     ___      ___   _______  _______  _______  _______  _______  _______  ___        #
#    |   |    |   | |       ||       ||       ||       ||       ||   _   ||   |       #
#    |   |    |   | |    ___||    ___||  _____||_     _||    ___||  |_|  ||   |       #
#    |   |    |   | |   |___ |   |___ | |_____   |   |  |   |___ |       ||   |       #
#    |   |___ |   | |    ___||    ___||_____  |  |   |  |    ___||       ||   |___    #
#    |       ||   | |   |    |   |___  _____| |  |   |  |   |___ |   _   ||       |   #
#    |_______||___| |___|    |_______||_______|  |___|  |_______||__| |__||_______|   #
# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
#
# - - - - - - - - - - - - - - - - - -
# This is the configuration file for
# my plugin LifeSteal. This plugin
# is extremely configurable and
# this is where you can configure
# everything.
#
# If you're confused, then please
# join our discord
# https://tomsoz.xyz/discord
# - - - - - - - - - - - - - - - - - -

# This is the amount of health that is removed on each death.
# 2 health = 1 heart
removePerDeath: 2

# This is the amount of health that is added on each kill.
# 2 health = 1 heart
addPerKill: 2

# This is the maximum amount of health that a player can have. This does not include +5 max
# hearts.
# If that recipe is enabled please take this into consideration.
# 2 health = 1 heart
maxHealth: 40

# This is the minimum amount of health that a player can have. If they are at this point
# then they won't give any health for being killed and won't lose any on death unless banIfOutOfHearts is enabled.
# 2 health = 1 heart
minHealth: 2

# The maximum amount of times one player can use the +5 Max Hearts item.
plusMaxHeartLimit: 2

# These are the only worlds that LifeSteal works in. Nothing in LifeSteal will work in worlds
# that aren't on this list.
# (Case Sensitive)
onlyWorkIn: ["world", "world_nether", "world_the_end"]

# If this is true then if a user reaches below the minHealth as defined above they will be banned from the server.
banIfOutOfHearts: true

# The command to ban people with. Only used if banIfOutOfHearts is enabled.
banCommand: "ban %eliminated% Out of hearts!"

# The command to unban a user if they are revived.
unbanCommand: "unban %eliminated% Revived!"

# This allows players to craft the revive book and use it to bring back a player that has been eliminated.
useReviveBook: true

# How much health a person who has just been revived has. Beware this could lead to duping hearts.
# 2 health = 1 heart
revivedHealth: 10.0

# These are all recipes that are in the plugin and where you can toggle them.
# To find out the actual crafting recipes check the plugin's spigot page.
recipes:
  # +1 Heart
  addHeart:
    enabled: true
    recipe:
      - ""
      - ""
      - ""

  # -1 Heart
  removeHeart: true

  # +5 Max Hearts
  add5MaxHearts: true

  # Enchanted Golden Apple
  enchantedGoldenApple: true

  # Using heart fragments
  heartFragments: true

  # Allows the crafting of revive books.
  reviveBook: true

# These are the mobs that can drop heart fragments.
heartFragmentMobs:
  # The 1 means it is a 1% chance to drop one.
  villager: 1
  zombie: 1

lootChances:
  # Percentage chances of heart fragments.
  # Set to 0 to disable
  abandoned_mineshaft: 5
  ancient_city: 30
  bastion: 15
  buried_treasure: 10
  desert_pyramid: 10
  end_city: 50
  igloo: 5
  jungle_temple: 15
  ruined_portal: 10
  shipwreck_treasure: 12
  simple_dungeon: 4
  stronghold: 25
  woodland_mansion: 15
  village: 3